name: Trigger auto deployment for test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test-AutoDeployTrigger-82faa77f-41c4-4b2a-938d-b0f3d72e3b62.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistry3viwetoqeu7r6.azurecr.io
          registryUsername: ${{ secrets.TEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TEST_REGISTRY_PASSWORD }}
          containerAppName: test
          resourceGroup: airwavesapi938a
          imageToBuild: containerregistry3viwetoqeu7r6.azurecr.io/test:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


